### ISSUE TITLE
PyRubberband import error

### ISSUE THREAD

**Issue by jpauwels** [migperfer/harmonic_compatibility#1]
Hi Miguel

I'd like to check out your work, but I'm running into an `ImportError` in `harmonic_compatibility/utils/mix.py` immediately. My version 0.3.0 of pyrubberband does not include a `frequency_multiply` function, and I can't find anything about it [in the docs](https://pyrubberband.readthedocs.io/en/0.3.0/) either. Are you using a special build?

**Comment by migperfer** [comment]
Hi Johan,

Thanks for letting me know! Yes, I have indeed a [fork ](https://github.com/migperfer/pyrubberband/tree/more_base_functions) of pyrubberband for this function. There is also a [pull request](https://github.com/bmcfee/pyrubberband/pull/19) for this to the original pyrubberband, but for now I think the only way is to stick to my fork.

Thanks again for letting me know! I will update the readme!

**Comment by jpauwels** [comment]
Great, all working now, thanks. Let's hope your PR gets merged soon.
